_BASE_: [
  '../datasets/hysteroma_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1700e.yml',
  '_base_/ssdlite_mobilenet_v3_large_320.yml',
  '_base_/ssdlite320_reader.yml',
]

weights: outputs/hysteroma_ssd/model_final

epoch: 1000

worker_num: 8

TrainReader:
  inputs_def:
    num_max_boxes: 8
  sample_transforms:
    - Decode: {}
    - RandomDistort: {brightness: [0.5, 1.125, 0.875], random_apply: False}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {allow_no_crop: Fasle}
    - RandomFlip: {}
    - Resize: {target_size: [320, 320], keep_ratio: False, interp: 1}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 90}
  batch_transforms:
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: true}
    - Permute: {}
  batch_size: 64
  shuffle: true
  drop_last: true

EvalReader:
  inputs_def:
    num_max_boxes: 8
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [300, 300], keep_ratio: False, interp: 1}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: true}
    - Permute: {}
  batch_size: 64

TestReader:
  inputs_def:
    image_shape: [3, 300, 300]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [300, 300], keep_ratio: False, interp: 1}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: true}
    - Permute: {}
  batch_size: 1
