metric: COCO
num_classes: 2

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/train.json
    dataset_dir: dataset/hysteroma
    data_fields: ['image', 'gt_bbox', 'gt_class']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/val.json
    dataset_dir: dataset/hysteroma

TestDataset:
  !ImageFolder
    anno_path: annotations/val.json # also support txt (like VOC's label_list.txt)
    dataset_dir: dataset/hysteroma # if set, anno_path will be 'dataset_dir/anno_path'
